
import React, { useState, useMemo } from 'react';
import { useData } from '../../context/DataContext';
import { Client, ProductType, UserRole } from '../../types';
import { Search, Filter, Download, Edit2, X, Mail, Phone } from 'lucide-react';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';

export const Clients: React.FC = () => {
  const { clients, updateClient, user } = useData();
  const [searchTerm, setSearchTerm] = useState('');
  const [productFilter, setProductFilter] = useState<string>('All');
  
  // Edit State
  const [editingClient, setEditingClient] = useState<Client | null>(null);
  const [editForm, setEditForm] = useState<Partial<Client>>({});

  const filteredClients = useMemo(() => {
    let result = clients;
    
    // Role based filtering
    if (user?.role === UserRole.ADVISOR && user.productsSold) {
        result = result.filter(c => user.productsSold!.includes(c.product));
    }

    if (productFilter !== 'All') {
        result = result.filter(c => c.product === productFilter);
    }

    if (searchTerm) {
        const lower = searchTerm.toLowerCase();
        result = result.filter(c => 
            c.name.toLowerCase().includes(lower) || 
            c.policyNumber.toLowerCase().includes(lower) ||
            c.email?.toLowerCase().includes(lower)
        );
    }
    
    return result;
  }, [clients, user, productFilter, searchTerm]);

  const handleEdit = (client: Client) => {
      setEditingClient(client);
      setEditForm({...client});
  };

  const handleSave = (e: React.FormEvent) => {
      e.preventDefault();
      if (editingClient && editForm) {
          updateClient(editingClient.id, editForm);
          setEditingClient(null);
      }
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(20);
    doc.text("Client Roster", 14, 22);
    doc.setFontSize(11);
    doc.text(`Generated by: ${user?.name}`, 14, 30);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 36);

    const tableColumn = ["Name", "Policy #", "Product", "Premium", "Renewal", "Phone"];
    const tableRows: any[] = [];

    filteredClients.forEach(client => {
      const clientData = [
        client.name,
        client.policyNumber,
        client.product,
        `$${client.premium.toLocaleString()}`,
        new Date(client.renewalDate).toLocaleDateString(),
        client.phone || 'N/A',
      ];
      tableRows.push(clientData);
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 44,
    });

    doc.save("clients_report.pdf");
  };

  const getStatusColor = (renewalDate: string) => {
      const today = new Date();
      const renewal = new Date(renewalDate);
      const diffTime = renewal.getTime() - today.getTime();
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      if (diffDays < 0) return 'bg-red-100 text-red-700 border-red-200'; // Expired
      if (diffDays < 30) return 'bg-yellow-100 text-yellow-700 border-yellow-200'; // Renewing Soon
      return 'bg-green-100 text-green-700 border-green-200'; // Active
  };

  const getStatusText = (renewalDate: string) => {
      const today = new Date();
      const renewal = new Date(renewalDate);
      const diffTime = renewal.getTime() - today.getTime();
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      if (diffDays < 0) return 'Expired';
      if (diffDays < 30) return 'Renewing Soon';
      return 'Active';
  };

  return (
    <div className="space-y-8 pb-10">
        <div className="flex flex-col md:flex-row justify-between items-end gap-4">
            <div>
                <h1 className="text-2xl font-bold text-[#0B2240]">Client Management</h1>
                <p className="text-slate-500">View policies, renewals, and client contact details.</p>
            </div>
            <button 
                onClick={generatePDF}
                className="bg-white border border-slate-200 text-slate-700 px-6 py-3 rounded-full font-bold text-sm hover:bg-slate-50 transition-colors flex items-center gap-2"
            >
                <Download className="h-4 w-4" /> Export Report
            </button>
        </div>

        <div className="bg-white rounded-[2rem] shadow-sm border border-slate-100 overflow-hidden">
            {/* Controls */}
            <div className="p-6 border-b border-slate-100 flex flex-col md:flex-row gap-4">
                <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                    <input 
                        type="text" 
                        placeholder="Search clients..." 
                        value={searchTerm}
                        onChange={e => setSearchTerm(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 bg-white border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-[#0A62A7] focus:border-transparent text-slate-900"
                    />
                </div>
                <div className="relative">
                    <select 
                        className="bg-slate-50 text-slate-700 border border-slate-200 rounded-xl px-6 py-3 text-sm font-bold focus:ring-2 focus:ring-[#0A62A7] focus:border-transparent appearance-none pr-10 cursor-pointer"
                        value={productFilter}
                        onChange={e => setProductFilter(e.target.value)}
                    >
                        <option value="All">All Products</option>
                        {Object.values(ProductType).map(p => <option key={p} value={p}>{p}</option>)}
                    </select>
                    <Filter className="absolute right-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                </div>
            </div>

            <div className="overflow-x-auto">
                <table className="w-full text-left text-sm text-slate-600">
                    <thead className="bg-slate-50 text-xs uppercase font-bold text-slate-500">
                        <tr>
                            <th className="px-6 py-4">Client Name</th>
                            <th className="px-6 py-4">Policy Info</th>
                            <th className="px-6 py-4">Premium</th>
                            <th className="px-6 py-4">Status</th>
                            <th className="px-6 py-4">Contact</th>
                            <th className="px-6 py-4">Carrier</th>
                            <th className="px-6 py-4 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {filteredClients.map(client => (
                            <tr key={client.id} className="hover:bg-slate-50/50 transition-colors group">
                                <td className="px-6 py-4">
                                    <div className="font-bold text-[#0B2240]">{client.name}</div>
                                    <div className="text-xs text-slate-400">{client.city}, {client.state}</div>
                                </td>
                                <td className="px-6 py-4">
                                    <div className="font-medium text-slate-700">{client.product}</div>
                                    <div className="text-xs text-slate-400 font-mono">{client.policyNumber}</div>
                                </td>
                                <td className="px-6 py-4 font-mono font-medium text-slate-700">
                                    ${client.premium.toLocaleString()}
                                </td>
                                <td className="px-6 py-4">
                                    <span className={`px-2.5 py-1 rounded-md text-[10px] font-bold uppercase border ${getStatusColor(client.renewalDate)}`}>
                                        {getStatusText(client.renewalDate)}
                                    </span>
                                    <div className="text-[10px] text-slate-400 mt-1">Renews: {new Date(client.renewalDate).toLocaleDateString()}</div>
                                </td>
                                <td className="px-6 py-4">
                                    <div className="flex gap-2">
                                        {client.email && (
                                            <a href={`mailto:${client.email}`} className="p-1.5 bg-blue-50 text-blue-600 rounded-lg hover:bg-blue-100" title={client.email}>
                                                <Mail className="h-3.5 w-3.5" />
                                            </a>
                                        )}
                                        {client.phone && (
                                            <a href={`tel:${client.phone}`} className="p-1.5 bg-green-50 text-green-600 rounded-lg hover:bg-green-100" title={client.phone}>
                                                <Phone className="h-3.5 w-3.5" />
                                            </a>
                                        )}
                                    </div>
                                </td>
                                <td className="px-6 py-4 text-xs font-bold text-slate-500">
                                    {client.carrier || 'N/A'}
                                </td>
                                <td className="px-6 py-4 text-right">
                                    <button 
                                        onClick={() => handleEdit(client)}
                                        className="p-2 hover:bg-slate-100 rounded-lg text-slate-400 hover:text-blue-600 transition-colors"
                                    >
                                        <Edit2 className="h-4 w-4" />
                                    </button>
                                </td>
                            </tr>
                        ))}
                        {filteredClients.length === 0 && (
                            <tr>
                                <td colSpan={7} className="px-6 py-12 text-center text-slate-400 italic">No clients found matching criteria.</td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </div>

        {/* Edit Modal */}
        {editingClient && (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0B2240]/50 backdrop-blur-sm p-4">
                <div className="bg-white rounded-[2rem] shadow-2xl w-full max-w-lg p-8 animate-fade-in max-h-[90vh] overflow-y-auto">
                    <div className="flex justify-between items-center mb-6">
                        <h2 className="text-xl font-bold text-[#0B2240]">Edit Client</h2>
                        <button onClick={() => setEditingClient(null)} className="p-2 hover:bg-slate-100 rounded-full"><X className="h-5 w-5 text-slate-400" /></button>
                    </div>
                    <form onSubmit={handleSave} className="space-y-4">
                        <div>
                            <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Client Name</label>
                            <input 
                                className="w-full bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7]"
                                value={editForm.name || ''}
                                onChange={e => setEditForm({...editForm, name: e.target.value})}
                            />
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Email</label>
                                <input 
                                    className="w-full bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7]"
                                    value={editForm.email || ''}
                                    onChange={e => setEditForm({...editForm, email: e.target.value})}
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Phone</label>
                                <input 
                                    className="w-full bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7]"
                                    value={editForm.phone || ''}
                                    onChange={e => setEditForm({...editForm, phone: e.target.value})}
                                />
                            </div>
                        </div>
                        <div>
                            <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Address</label>
                            <input 
                                className="w-full bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7] mb-2"
                                placeholder="Street"
                                value={editForm.street || ''}
                                onChange={e => setEditForm({...editForm, street: e.target.value})}
                            />
                            <div className="grid grid-cols-3 gap-2">
                                <input 
                                    className="col-span-1 bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7]"
                                    placeholder="City"
                                    value={editForm.city || ''}
                                    onChange={e => setEditForm({...editForm, city: e.target.value})}
                                />
                                <input 
                                    className="col-span-1 bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7]"
                                    placeholder="State"
                                    value={editForm.state || ''}
                                    onChange={e => setEditForm({...editForm, state: e.target.value})}
                                />
                                <input 
                                    className="col-span-1 bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7]"
                                    placeholder="Zip"
                                    value={editForm.zip || ''}
                                    onChange={e => setEditForm({...editForm, zip: e.target.value})}
                                />
                            </div>
                        </div>
                        <div className="grid grid-cols-2 gap-4 pt-4 border-t border-slate-100">
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Premium ($)</label>
                                <input 
                                    type="number"
                                    className="w-full bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7]"
                                    value={editForm.premium || ''}
                                    onChange={e => setEditForm({...editForm, premium: Number(e.target.value)})}
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Renewal Date</label>
                                <input 
                                    type="date"
                                    className="w-full bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7]"
                                    value={editForm.renewalDate || ''}
                                    onChange={e => setEditForm({...editForm, renewalDate: e.target.value})}
                                />
                            </div>
                        </div>
                        <div className="pt-4">
                            <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Carrier</label>
                            <input 
                                className="w-full bg-white text-slate-900 border border-slate-300 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-[#0A62A7]"
                                value={editForm.carrier || ''}
                                onChange={e => setEditForm({...editForm, carrier: e.target.value})}
                            />
                        </div>
                        <div className="pt-4 flex gap-3">
                            <button type="button" onClick={() => setEditingClient(null)} className="flex-1 py-3 rounded-xl font-bold text-slate-500 hover:bg-slate-50 transition-colors">Cancel</button>
                            <button type="submit" className="flex-1 py-3 rounded-xl font-bold bg-[#0A62A7] text-white hover:bg-blue-700 transition-colors shadow-lg shadow-blue-900/20">Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
        )}
    </div>
  );
};
